import numpy as np 
n = np.array([[2,3,4,5],[6,4,5,8]])
x = np.ones(9)
y = x.reshape(3,3)
z = y[0][1]+1
y[0][1] = z
p = y.flatten()
print(x)
print(y)
print(z)
print(p)
print(n)
print(n[0][1])
a = np.arange(12)
print("a-->",a)
b = a.reshape(3,4)
print(b)
c = a.reshape(2,6)
print(c)
d = a.reshape(2,3,2)
print(d)
e = np.array([[5,3,9],[8,11,0],[4,8,3]])
print("e")
print(e)
dia = np.diagonal(e)
print("diagonal",dia)
s = np.sort(e)
print("sorted e row wise")
print(s)
s1= np.sort(e,axis=0)
print("sorted e column wise")
print(s1)
t = np.transpose(s1)
print("transposing s1")
print(t)
m1 = np.matrix('1 2 3;4 5 7;7 8 9')
print("matrix m1")
print(m1)
m2 = np.matrix('1 4 3;4 -5 7;6 11 9')
print("printing second matrix")
print(m2)
print("adding two matrixes")
print(m1+m2)
print("simialrly we cam mutipy,sub etc")
ran = np.random.rand(12)
print("12 random numbers")
print(ran)
("rearranging random mu,bers")
ran1 = ran.reshape(2,2,3)
print(ran1)